#
#    Copyright (c) 2026 Manuel Hilgert
#
#    See the file LICENSE for your full rights.
#
"""Build the field catalog from Werner Krenn's ecowittcustom driver.

The catalog is data, not code, and it should stay traceable to where it came from.
Rather than retyping five hundred field names, this reads them out of the source with
the ast module and writes catalogs/ecowitt.py.

Usage:

    python tools/import_catalog.py path/to/ecowittcustom.py

The result is reviewed and committed like any other file. Run it again when upstream
adds fields, and the diff shows exactly what changed.
"""

import argparse
import ast
import os.path
import re
import sys
from typing import Dict, List

HEADER = '''#
#    Copyright (c) 2016-2020 Matthew Wall
#    Copyright (c) 2025-2026 Werner Krenn
#    Copyright (c) 2026 Manuel Hilgert
#
#    See the file LICENSE for your full rights.
#
"""What the hardware sends, and where it belongs in WeeWX.

Generated by tools/import_catalog.py from the ecowittcustom driver by Werner Krenn,
https://github.com/WernerKr/Ecowitt-or-DAVIS-stations-and-Season-skin, which is itself
descended from the interceptor driver by Matthew Wall. Both are GPLv3, and so is this.

Do not edit by hand. Run the tool again instead, so that the next update upstream stays
a reviewable diff.

Source: {source}
Fields: {count}
"""

# Raw field name as the hardware sends it -> the WeeWX field it belongs in.
FIELDS = {{
{fields}}}

# WeeWX field -> unit group, for the fields that are not already in the WeeWX schema.
GROUPS = {{
{groups}}}

# Raw field prefixes whose target name says more than the hardware does. A reading from
# one of these is in the right unit and the right channel, but whether it belongs to
# soil, a pool or a wall is the user's to say, with field_map_extensions.
PLACEMENT_UNKNOWN = {{
{placement}}}

# Raw field prefix -> (sensor model, how many channels it can have). From the
# compatibility table Ecowitt publishes. A channel beyond these does not exist, so
# nothing should be derived for it.
CHANNELS = {{
{channels}}}

# Raw field -> where another driver puts it, for every field this one places
# differently. Generated from REMAP and OVERRIDES, so it cannot drift from them.
#
# These are not written until the user says where they want them. Either answer can
# be the one that continues somebody's history, and the wrong one puts two sensors in
# one column, which nothing afterwards can separate.
CONTESTED = {{
{contested}}}

# The driver those other placements come from.
CONTESTED_WITH = 'ecowittcustom'
'''


# How many channels each family can have, from the compatibility table Ecowitt
# publishes for its consoles and gateways. These are the highest figures a current
# console supports; an older one may allow fewer.
#
# Two rows of that table settle questions the field names cannot:
#
#   The WN34 is one row, "WN34 S/L/D". The spike, the PVC lead and the silicone lead
#   are one device as far as the console and the protocol are concerned, so nothing in
#   an upload says which of them sent a reading.
#
#   WH51/WH51L and WH52 share a single cell of 16, so they share the channel numbers
#   too. soilmoisture3 and soil_ec_hum3 are the same channel with a different sensor
#   in it, not two sensors fighting over one field.
CHANNELS = {}

# Every raw family a sensor reports on, so that a limit covers the readings, the
# battery and the signal alike.
for _model, _count, _prefixes in [
    ('WH31', 8, ['temp', 'humidity', 'batt', 'wh31rssi', 'wh31sig']),
    ('WN34', 8, ['tf_ch', 'tf_batt', 'wh34rssi', 'wh34sig']),
    ('WN35', 8, ['leafwetness_ch', 'leaf_batt', 'wh35rssi', 'wh35sig']),
    ('WH51', 16, ['soilmoisture', 'soilbatt', 'soilad', 'wh51rssi', 'wh51sig']),
    (
        'WH52',
        16,
        [
            'soil_ec_hum',
            'soil_ec_hum_ad',
            'soil_ec_temp',
            'soil_ec_batt',
            'soil_ec_ad',
            'soil_ec',
        ],
    ),
    ('WH41', 4, ['pm25_ch', 'pm25batt', 'pm25_avg_24h_ch', 'wh41rssi', 'wh41sig']),
    ('WH55', 4, ['leak_ch', 'leakbatt', 'wh55rssi', 'wh55sig']),
    (
        'LDS01',
        4,
        [
            'air_ch',
            'depth_ch',
            'thi_ch',
            'ldsbatt',
            'ldsheat_ch',
            'ldspw_ch',
            'wh54sig',
            'wh54rssi',
            'wh54_ch',
        ],
    ),
]:
    for _prefix in _prefixes:
        CHANNELS[_prefix] = (_model, _count)

# Families where the WeeWX field name claims something the hardware never said. These
# are multi-channel sensors: the same model reports on the same field whether it is a
# probe in a flower bed, a silicone lead in a pool, or a sensor on a north wall. The
# mapping has to put them somewhere, and somewhere is not the same as knowing.
#
# This is hardware knowledge, so it cannot be read out of the upstream source. It is
# kept here, next to the tool that writes the catalog.
PLACEMENT_UNKNOWN = {
    'tf_ch': "WN34 multi-channel temperature. Sold with a spike, with a PVC lead, and "
    "with a silicone lead for a pool. All of them report as tf_chN, so the "
    "channel is theirs and the placement is yours. They go to extraTemp9 and "
    "up, which is where the Ecowitt gateway driver puts them.",
    'temp': "WH31 multi-channel temperature and humidity. Placement is the user's.",
    'leafwetness_ch': "WN35 leaf wetness. Placement is the user's.",
}

# Whole families we place differently from upstream. Each entry is a pattern, a
# function from the channel number to the WeeWX field, and the unit group.
REMAP = [
    # The WN34 is not a soil sensor. It is a multi-channel thermometer, sold with a
    # spike, with a PVC lead, and with a silicone lead for a pool. Upstream sends it to
    # soilTemp, which claims a placement the hardware never gave, and which takes the
    # soil fields away from the sensors that really are in the ground.
    #
    # extraTemp9 and up is where the Ecowitt gateway driver puts it, i.e. the driver
    # most people are coming from, so this also means their history lines up.
    (r'^tf_ch(\d+)$', lambda n: 'extraTemp%d' % (n + 8), 'group_temperature'),
    # Its battery goes with it, named like the signal fields already in the catalog.
    (r'^tf_batt(\d+)$', lambda n: 'wn34_ch%d_batt' % n, 'group_volt'),
    # With the WN34 out of the way, soilTemp belongs to the sensor that really is in
    # the ground. A WH52 measures moisture, temperature and conductivity in one probe,
    # and there is no doubt about where it sits. Upstream leaves its temperature on
    # soilmTemp, which no skin looks for.
    (r'^soil_ec_temp(\d+)$', lambda n: 'soilTemp%d' % n, 'group_temperature'),
]

_REMAP = [(re.compile(pattern), name, group) for pattern, name, group in REMAP]

# Where we knowingly differ from upstream, and why. Each of these is a decision, so it
# is written down rather than left in a commit message.
OVERRIDES = {
    # Upstream puts the time of the last strike into lightning_disturber_count, which
    # counts something else entirely. A Unix timestamp in a counter shows up in reports
    # as a ten digit number of strikes.
    'lightning_time': ('lightning_time', 'group_time'),
}


# Families that share their channel numbers, so two raw names for one field are the
# same channel rather than a clash. The WH51 and the WH52 occupy one pool of 16.
SHARED = [
    ('soilmoisture', 'soil_ec_hum'),
    ('soilbatt', 'soil_ec_batt'),
    ('soilad', 'soil_ec_hum_ad'),
]


def _shares_channels(raws):
    """True if these raw names are the same channel seen through two sensor types."""
    stems = {re.sub(r'\d+$', '', raw) for raw in raws}
    return any(stems <= set(pair) for pair in SHARED)


def _remap(raw, groups):
    """Return the field a remapped family belongs on, or None."""
    for pattern, name_of, group in _REMAP:
        match = pattern.match(raw)
        if match:
            field = name_of(int(match.group(1)))
            groups[field] = group
            return field
    return None


def find_class(node, name):
    for child in ast.walk(node):
        if isinstance(child, ast.ClassDef) and child.name == name:
            return child
    raise SystemExit("Cannot find class %s" % name)


def const_assign(class_node, name):
    for statement in class_node.body:
        if isinstance(statement, ast.Assign) and any(
            getattr(t, 'id', None) == name for t in statement.targets
        ):
            return ast.literal_eval(statement.value)
    raise SystemExit("Cannot find %s" % name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', help="Path to ecowittcustom.py")
    parser.add_argument('--out', default='bin/user/ultimatepush/catalogs/ecowitt.py')
    parser.add_argument(
        '--schema',
        help="Path to WeeWX's wview_extended.py. Used to "
        "settle which target wins when upstream maps "
        "one reading to more than one field.",
    )
    args = parser.parse_args()

    schema_fields = set()
    if args.schema:
        with open(args.schema, encoding='utf-8') as fd:
            schema_fields = set(re.findall(r"\('(\w+)',\s+'\w+'\)", fd.read()))

    with open(args.source, encoding='utf-8', errors='replace') as fd:
        source = fd.read()
    tree = ast.parse(source)

    # Raw field -> intermediate name, from the Ecowitt parser.
    label_map = const_assign(
        find_class(find_class(tree, 'EcowittClient'), 'Parser'), 'LABEL_MAP'
    )
    # WeeWX field -> intermediate name, from the shared consumer.
    sensor_map = const_assign(find_class(tree, 'Consumer'), 'DEFAULT_SENSOR_MAP')
    # WeeWX field -> unit group, assigned at import time in the driver.
    groups = dict(
        re.findall(
            r"^weewx\.units\.obs_group_dict\['([^']+)'\]\s*=\s*'([^']+)'", source, re.M
        )
    )

    # The two maps meet in the middle, at the intermediate name. Collapse them, so that
    # a lookup here is one step rather than two.
    by_intermediate = {}  # type: Dict[str, List[str]]
    for weewx_field, intermediate in sensor_map.items():
        by_intermediate.setdefault(intermediate, []).append(weewx_field)

    fields = {}
    unresolved = []
    ambiguous = []
    contested = {}
    for raw, intermediate in sorted(label_map.items()):
        targets = by_intermediate.get(intermediate)
        upstream = sorted(targets)[0] if targets else None
        if raw in OVERRIDES:
            fields[raw], groups[OVERRIDES[raw][0]] = OVERRIDES[raw]
            if upstream and upstream != fields[raw]:
                contested[raw] = upstream
            continue
        remapped = _remap(raw, groups)
        if remapped:
            fields[raw] = remapped
            if upstream and upstream != remapped:
                contested[raw] = upstream
            continue
        if not targets:
            unresolved.append(raw)
            continue
        if len(targets) > 1:
            # A schema field wins, because that is what skins and reports look for. A
            # battery on outTempBatteryStatus shows up in the Seasons sensor panel; the
            # same reading on wh65_batt does not.
            preferred = sorted(t for t in targets if t in schema_fields)
            if preferred:
                chosen = preferred[0]
            elif raw in targets:
                # No schema field to settle it, but one target is the raw name itself.
                # Prefer that over a variant spelling of it.
                chosen = raw
            else:
                chosen = sorted(targets)[0]
            ambiguous.append((raw, chosen, sorted(set(targets) - {chosen})))
            fields[raw] = chosen
        else:
            fields[raw] = targets[0]

    used_groups = {f: g for f, g in sorted(groups.items()) if f in set(fields.values())}

    def render(mapping):
        # repr, not quotes of our own: some of these values contain an apostrophe.
        return ''.join("    %r: %r,\n" % (k, v) for k, v in sorted(mapping.items()))

    with open(args.out, 'w', encoding='utf-8', newline='\n') as fd:
        fd.write(
            HEADER.format(
                source=os.path.basename(args.source),
                count=len(fields),
                fields=render(fields),
                groups=render(used_groups),
                placement=render(PLACEMENT_UNKNOWN),
                channels=render(CHANNELS),
                contested=render(contested),
            )
        )

    print("%d fields, %d unit groups -> %s" % (len(fields), len(used_groups), args.out))
    if contested:
        print(
            "%d fields are placed differently from upstream, so they will not be "
            "written until the user says which placement they want:" % len(contested)
        )
        for raw in sorted(contested)[:4]:
            print("  %-20s here %-18s upstream %s" % (raw, fields[raw], contested[raw]))
        if len(contested) > 4:
            print("  ... and %d more" % (len(contested) - 4))
    if ambiguous:
        print("%d readings had more than one target upstream:" % len(ambiguous))
        for raw, chosen, rest in ambiguous:
            print("  %-22s -> %-24s (not %s)" % (raw, chosen, ', '.join(rest)))
    collisions = {}  # type: Dict[str, List[str]]
    for raw, field in fields.items():
        collisions.setdefault(field, []).append(raw)
    collisions = {
        f: sorted(r)
        for f, r in collisions.items()
        if len(r) > 1 and not _shares_channels(r)
    }
    if collisions:
        print(
            "%d fields are written by more than one reading. Whichever arrives last "
            "wins:" % len(collisions)
        )
        for field, raws in sorted(collisions.items())[:6]:
            print("  %-22s <- %s" % (field, ', '.join(raws)))
        if len(collisions) > 6:
            print("  ... and %d more" % (len(collisions) - 6))
    if unresolved:
        print(
            "%d raw fields have no WeeWX target upstream, left out:" % len(unresolved),
            file=sys.stderr,
        )
        print("  " + ' '.join(unresolved), file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
